### ISSUE TITLE
 TLS 1.3 Problem

### ISSUE THREAD

**Issue by sckn** [khs1994-website/tls-1.3#2]
Hello,
I have run a container. But browser and nginx talk with TLS1.2. Can't talk TLS 1.3

Firefox 60.0.2
Version 67.0.3396.79 (Official Build) (64-bit)

Where is my mistake ?

**Comment by khs1994** [comment]
show me your nginx conf

**Comment by sckn** [comment]
`  listen                     443 ssl http2;
  server_name                www.t.khs1994.com;
  root                       /app/test;
  index                      index.html index.htm index.php;

  ssl_certificate            conf.d/ssl/www.t.khs1994.com.crt;
  ssl_certificate_key        conf.d/ssl/www.t.khs1994.com.key;

  ssl_session_cache          shared:SSL:1m;
  ssl_session_timeout        5m;
  ssl_protocols              TLSv1.2 TLSv1.3;
  ssl_ciphers                'TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES128-GCM-SHA256:TLS13-AES256-GCM-SHA384:TLS13-AES128-CCM-SHA256:TLS13-AES128-CCM-8-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';

  ssl_prefer_server_ciphers  on;
  ssl_stapling               on;
  ssl_stapling_verify        on;

  # location / {
  #   try_files $uri $uri/ /index.php?$query_string;
  # }
  #
  # location ~ .*\.php(\/.*)*$ {
  #   fastcgi_pass   php7:9000;
  #   include        fastcgi.conf;
  # }
}
`

**Comment by khs1994** [comment]
Change browser settings

FireFox `about:config` -> `security.tls.version.max` -> change 3 to  4

Chrome `chrome://flags` -> `TLS 1.3` -> `Enable ...`

**Comment by sckn** [comment]
Yes,
I have already a configure in my browsers but doesn't work.
What is your browser version ?

**Comment by khs1994** [comment]
![default](https://user-images.githubusercontent.com/16733187/41279029-f78b9270-6e5d-11e8-90e4-282f9dc17a19.png)

show me this photo

**Comment by khs1994** [comment]
I use firefox dev release, maybe you can try it 

https://ftp.mozilla.org/pub/firefox/releases/61.0b13/

**Comment by khs1994** [comment]
update, please read readme.md
